# Generated by Django 3.2.9 on 2022-01-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20220104_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.CharField(default='部署なし', max_length=32),
        ),
        migrations.AlterField(
            model_name='officer',
            name='area',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='offices.area', to_field='code'),
        ),
    ]
