# Generated by Django 3.2.9 on 2022-01-04 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16, unique=True)),
                ('word_family', models.IntegerField()),
                ('word_relative', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16, unique=True)),
                ('word_family', models.IntegerField()),
                ('word_relative', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16, unique=True)),
                ('word_family', models.IntegerField()),
                ('word_relative', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name_End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16, unique=True)),
                ('word_family', models.IntegerField()),
                ('word_relative', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name_Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16, unique=True)),
                ('word_family', models.IntegerField()),
                ('word_relative', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=32, unique=True)),
                ('word_id_serial', models.CharField(max_length=255, unique=True)),
                ('word_family_id_serial', models.CharField(max_length=255)),
                ('is_std', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='words.joint')),
                ('name_end', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='words.name_end')),
                ('name_start', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='words.name_start')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=32, unique=True)),
                ('word_id_serial', models.CharField(max_length=255, unique=True)),
                ('word_family_id_serial', models.CharField(max_length=255)),
                ('core_item_id', models.CharField(blank=True, max_length=16, null=True)),
                ('opt_item_id', models.CharField(blank=True, max_length=16, null=True)),
                ('is_core_std', models.BooleanField(default=False)),
                ('is_opt_std', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_end', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='words.item_end')),
                ('item_start', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='words.item_start')),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='words.joint')),
            ],
        ),
        migrations.AddConstraint(
            model_name='service_item',
            constraint=models.UniqueConstraint(fields=('item_start', 'joint', 'item_end'), name='unique_word'),
        ),
    ]
