# Generated by Django 3.2.9 on 2022-01-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_item',
            name='is_app_con',
            field=models.BooleanField(default=False),
        ),
    ]
