# Generated by Django 3.2.9 on 2022-01-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace_keeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_stock',
            name='core_serv_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service_stock',
            name='opt_items_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
