# Generated by Django 3.2.9 on 2022-01-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20220104_1445'),
        ('peace_keeping', '0002_auto_20220105_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_service',
            name='my_num_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='res_my_num_id', to='offices.resident', to_field='my_num_id'),
        ),
    ]
