# Generated by Django 4.0.1 on 2022-01-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace_keeping', '0003_alter_used_service_my_num_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_stock',
            name='ex_serv_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
